### ISSUE TITLE
Support the same kinds of file types in GitHub.com and GHE

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/github#16]
<img width="801" alt="screen shot 2015-08-13 at 10 01 41 am" src="https://cloud.githubusercontent.com/assets/95672/9251679/6b377b9e-41a2-11e5-9619-8d65d61f5acc.png">

**Comment by kevinSuttle** [comment]
GitHub.com
![screen shot 2016-02-12 at 12 02 06 pm](https://cloud.githubusercontent.com/assets/95672/13014152/75e1c630-d180-11e5-85de-7729cbcd3b8e.png)

GHE 2.4
![screen shot 2016-02-12 at 12 02 39 pm](https://cloud.githubusercontent.com/assets/95672/13014172/8d52e6be-d180-11e5-8f31-d23ee0e703c3.png)

**Comment by azenMatt** [comment]
For the ZenHub-able label, we still support all file-type uploads. 

Although we are looking at reducing or removing this feature as GitHub expands their file uploads. 

I imagine GHE 2.5 now has the updated file type list as it seems GHE updates are generally 4-6 weeks being the .com updates?

**Comment by kevinSuttle** [comment]
@azenMatt Nope. Even as of 2.5.2, still no parity. I think since the focus has been on improving GitHub.com, less attention has gone into GHE, which sucks. 

https://enterprise.github.com/releases/2.5.2

**Comment by kevinSuttle** [comment]
This landed in GitHub.com on Sept. 25 of last year. Closer to 6 _months_ than 6 weeks. https://github.com/blog/2061-attach-files-to-comments

**Comment by azenMatt** [comment]
Thanks @kevinSuttle - that is good to know. 

The ZenHub file upload will be dropping off GitHub.com this week (along with +1's now that we have reactions). We were planning on doing the same for Enterprise in our April release - but we will hold off on the upload changes in Enterprise until it at least has the same support from GH

**Comment by kevinSuttle** [comment]
Actually, I just confirmed that we do have this. Weird. https://twitter.com/bkeepers/status/709807428708110336
