### ISSUE TITLE
Thank contributors during PR merges

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/github#2]
via https://twitter.com/stephenplusplus/status/614095627048370180 @stephenplusplus
![image](https://cloud.githubusercontent.com/assets/95672/8962085/bbb39c96-35e6-11e5-95bb-fe2a0078d53b.png)

**Comment by sindresorhus** [comment]
In the meantime it could be a browser extension.

**Comment by kevinSuttle** [comment]
True true. http://zenhub.io has +1s.

**Comment by kevinSuttle** [comment]
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
