### ISSUE TITLE
Serve github.io with https by default

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/github#29]
Not sure if this would cause issues with custom domains, but it seems like a good idea to make use a wildcard SSL for github.io, possibly using @letsencrypt.

**Comment by tony7134** [comment]
Yes, this is a great idea. https://github.com/isaacs/github/issues/156

**Comment by kevinSuttle** [comment]
Ha, nice!

**Comment by kevinSuttle** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
