### ISSUE TITLE
PR code review sign-off

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/github#35]
Would be nice to have an official standard system for this. 

Here's how GitLab does it. 
<img width="371" alt="screen shot 2015-12-03 at 10 54 27 am" src="https://cloud.githubusercontent.com/assets/95672/11565505/4db61712-99ac-11e5-839c-46ecf1b2a045.png">
# 

@RyanFlorence's [+1 Chrome Extension](https://chrome.google.com/webstore/detail/github-%201s/lddfkkebajnpiicnpfamebilmhamkeme?utm_source=chrome-app-launcher-info-dialog) handles this creatively as well.

<img width="1020" alt="screen shot 2015-12-09 at 5 04 31 pm" src="https://cloud.githubusercontent.com/assets/95672/11700298/0a1b25ca-9e97-11e5-8d5e-dda3f33506f5.png">

**Comment by azenMatt** [comment]
I think this makes a lot of sense - if GitHub doesn't do it soon, we will steal it for ZenHub :smile:

**Comment by kevinSuttle** [comment]
Another one down. https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
