### ISSUE TITLE
Redirecting/transferring of issues

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/github#37]
It would be awesome to be able to move issues between repos. I realize the kind of havoc this would wreak on NGINX rules, but the UX solves a common problem (posting an issue in the wrong or not-as-relevant repo).

https://github.com/editorconfig/editorconfig/issues/245#issuecomment-163141459

**Comment by azenMatt** [comment]
For the ZenHub-able label - this is now live in ZenHub :smile: 

![image](https://cloud.githubusercontent.com/assets/7584089/13303786/1e15eed8-db06-11e5-9863-9ea653b8e334.png)

**Comment by kevinSuttle** [comment]
Woot, sure is!
