### ISSUE TITLE
Edit/add labels inline from within issues

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/github#7]
It's so annoying to have to stop in the middle of writing an issue to have to go and add or change and issue or milestone on a separate page. I would love to be able to edit these inline. 

<img width="298" alt="screen shot 2015-08-07 at 11 27 29 am" src="https://cloud.githubusercontent.com/assets/95672/9139318/8f67bbbe-3cf7-11e5-939f-faefeced60c5.png">
<img width="297" alt="screen shot 2015-08-07 at 11 28 49 am" src="https://cloud.githubusercontent.com/assets/95672/9139319/8f699f6a-3cf7-11e5-8423-26f977da999e.png">

**Comment by azenMatt** [comment]
Agreed! I would find this very useful for my workflow

**Comment by kevinSuttle** [comment]
This has been added very quietly. https://guides.github.com/features/issues/

**Comment by azenMatt** [comment]
Where abouts @kevinSuttle ? I don't see any changes

**Comment by kevinSuttle** [comment]
My mistake. I saw they added this for Milestones. Updated title to reflect. 

![https://guides.github.com/features/issues/milestones.png](https://guides.github.com/features/issues/milestones.png)

**Comment by azenMatt** [comment]
oh, ok - thanks 

I got way too excited when I saw this issue got closed that inline label changes had been added! 😄

**Comment by kevinSuttle** [comment]
Done https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/
